require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  TargetRailsVersion: 8.0
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'spec/examples.txt'

Layout/LineLength:
  Max: 120
  AllowedPatterns: ['\A\s*#']

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

# Naming cops
Naming/PredicateName:
  AllowedMethods:
    - has_many     # DSL method for defining relationships
    - has_one      # DSL method for defining relationships

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'lib/jpie/controller.rb'  # Core CRUD module with automatic method generation

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/jpie/controller.rb'  # CRUD method generation is longer

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'lib/jpie/controller.rb'  # class_methods block for CRUD generation

# Rails cops that don't apply to our gem
Rails/TimeZone:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# Gemspec cops that are acceptable for gems
Gemspec/DevelopmentDependencies:
  Enabled: false

# Capybara cops that are causing issues (rubocop bug)
Capybara/RSpec/PredicateMatcher:
  Enabled: false

# RSpec cops that are acceptable for our test style
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 1

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

# Style cops that are acceptable for test code
Style/OpenStructUse:
  Exclude:
    - 'spec/**/*'

# Lint cops that are acceptable for test initialization methods
Lint/MissingSuper:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*'

# Rails cops that we can ignore in test support files
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*' 